dist: xenial
language: minimal
service: docker

install:
    - docker pull keyiz/garnet-flow
    - docker run -d -it --name garnet keyiz/garnet-flow bash
    - docker cp ../garnet garnet:/
    - docker exec -i garnet bash -c "pip install -r /garnet/requirements.txt" 
    - docker exec -i garnet bash -c "pip install pytest python-coveralls"
    - docker exec -i garnet bash -c "pip install pytest-cov pytest-codestyle z3-solver" 
    # check CoSA dependencies
    - docker exec -i garnet bash -c "wget https://web.stanford.edu/~makaim/files/yosys-static -O ./bin/yosys"
    - docker exec -i garnet bash -c "chmod +x ./bin/yosys"
    - docker exec -i garnet bash -c "pysmt-install --confirm-agreement --msat"
    - docker exec -i garnet bash -c "pysmt-install --check"

    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    - docker cp Genesis2 garnet:/Genesis2

script:
    - docker exec -i garnet bash -c "/garnet/.travis/run.sh"
    # - docker exec -i garnet bash -c "cd garnet && python garnet.py --verilog && CoSA --problems ./tests/test_pe_tile_formal/problem.txt -v 3"
    # - docker exec -i garnet bash -c "cd garnet && yosys -p \"read_verilog -nomem2reg -sv ./garnet.v ./tests/AN2D0BWP16P90.sv ./tests/AO22D0BWP16P90.sv ./peak_core/CW_fp_mult.v ./peak_core/CW_fp_add.v; prep -top Tile_PE; hierarchy -check; memory -nomap; async2sync; flatten;; setundef -undriven -anyseq; write_btor __yosys_verilog__.btor2\""

after_success:
    - docker exec -i garnet bash -c "cd /garnet/ && coveralls"
