dist: xenial
language: minimal
service: docker

install:
    - docker pull keyiz/garnet-flow
    - docker run -d -it --name garnet keyiz/garnet-flow bash
    - docker cp ../garnet garnet:/
    - docker exec -i garnet bash -c "pip install -r /garnet/requirements.txt" 
    - docker exec -i garnet bash -c "pip install pytest python-coveralls"
    - docker exec -i garnet bash -c "pip install pytest-cov pytest-codestyle z3-solver" 
    # check CoSA dependencies
    - docker exec -i garnet bash -c "pysmt-install --confirm-agreement --msat"
    - docker exec -i garnet bash -c "pysmt-install --check"

    - git clone https://github.com/StanfordVLSI/Genesis2.git
    - rm -rf Genesis2/Genesis2Tools/PerlLibs/ExtrasForOldPerlDistributions/Compress
    - docker cp Genesis2 garnet:/Genesis2

script:
    # - docker exec -i garnet bash -c "/garnet/.travis/run.sh"
    docker exec -i garnet bash -c "CoSA --problems ./tests/test_pe_tile_formal/problem.txt -v 3"

after_success:
    - docker exec -i garnet bash -c "cd /garnet/ && coveralls"
